### PR TITLE
remove unused files

### PR DESCRIPTION
**Pull request by tkell**
@bmcfee, I don't think we need mailmap or appveyor, and I would argue against a makefile when we could just run `pytest` and `flake8`.

### CODE REVIEW

**Comment by bmcfee** [comment]
Agreed, but why get rid of appveyor?  It might be helpful to keep in there so that people get automated x-platform testing.

**Comment by tkell** [comment]
I'd say if we're not presenting something in the tutorial, we shouldn't have an extra file floating that we don't explain in the repo?

**Comment by bmcfee** [comment]
I think I'd rather keep it, document it, and mention it briefly (but not go into details).  The reason being that adding it back in later is more difficult than starting from a working config.

**Comment by tkell** [comment]
Suits me, will put it back!  One sec ...

**Pull request merged**
